plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id "kotlin-kapt"
    id 'kotlin-parcelize'
    id 'com.google.dagger.hilt.android'
    id 'androidx.navigation.safeargs'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'

}

android {
    namespace 'com.iw.android.prayerapp'
    compileSdk 34

    lint {
        baseline = file("lint-baseline.xml")
    }

    defaultConfig {
        applicationId "com.iw.android.prayerapp"
        minSdk 26
        targetSdk 34
        versionCode 10
        versionName "1.3"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures{
        dataBinding true
        viewBinding true
    }
}

dependencies {
    def datastore_preferences_version = "1.0.0"
    def coroutines_android_version = "1.5.2"
    def coroutines_core_version = "1.3.9"
    def lifecycle_version = "2.6.2"

    implementation platform('com.google.firebase:firebase-bom:32.8.1')

    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    //CircularTimerView
    implementation 'com.mikhaellopez:circularprogressbar:3.1.0'

    //Adhan
    implementation("com.batoulapps.adhan:adhan2:0.0.4")


    //Dots Indicator
    implementation("com.tbuonomo:dotsindicator:5.0")

    //SSP
    implementation 'com.intuit.ssp:ssp-android:1.1.0'

    //SDP
    implementation 'com.intuit.sdp:sdp-android:1.1.0'


    //Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:2.8.8"
    implementation "androidx.navigation:navigation-ui-ktx:2.8.8"
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.8.8"
    implementation("androidx.recyclerview:recyclerview:1.3.2")


    //gson
    implementation 'com.google.code.gson:gson:2.8.9'

    // GPS dependencies
    implementation("org.greenrobot:eventbus:3.3.1")
    implementation 'com.google.android.gms:play-services-location:21.0.0'

    //Datastore Preference
    implementation "androidx.datastore:datastore-preferences:$datastore_preferences_version"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"

    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

    // Saved state module for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"

    // Annotation processor
    kapt "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    //Dagger Hilt
    implementation "com.google.dagger:hilt-android:2.46"
    kapt "com.google.dagger:hilt-compiler:2.46"

    //Coroutine
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_android_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_core_version"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.1"

    //Custom Tab
    implementation 'androidx.browser:browser:1.5.0'
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"

    implementation 'com.akexorcist:round-corner-progress-bar:2.2.1'
    implementation 'com.tomergoldst.android:tooltips:1.1.1'
    implementation("org.greenrobot:eventbus:3.3.1")
    implementation("com.google.android.gms:play-services-location:21.0.0")
    implementation("com.google.android.libraries.places:places:3.3.0")
}