package com.iw.android.prayerapp.utils

import com.iw.android.prayerapp.R
import com.iw.android.prayerapp.data.response.SoundData

object GetAdhanSound {

    val adhansound = arrayListOf<SoundData>()
    val notificationsound = arrayListOf<SoundData>()

    init {
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit Short", R.raw.adhan_abdul_basit_short,false))
        adhansound.add(SoundData("Abdul Ghaffar", R.raw.adhan_abdul_ghaffar,false))
        adhansound.add(SoundData("Abdul Basit Short", R.raw.adhan_abdul_ghaffar_short,false))
        adhansound.add(SoundData("Abdul Hakam", R.raw.adhan_abdul_hakam,false))
        adhansound.add(SoundData("Abdul Hakam Short", R.raw.adhan_abdul_hakam_short,false))
        adhansound.add(SoundData("Abdul Nasir Harak", R.raw.adhan_abdul_nasir_harak,false))
        adhansound.add(SoundData("Abdul Nasir Harak Short", R.raw.adhan_abdul_nasir_harak_short,false))
        adhansound.add(SoundData("Abdul Rahman Al Hindi", R.raw.adhan_abdulrahman_al_hindi,false))
        adhansound.add(SoundData("Abdul Rahman Al Hindi Short", R.raw.adhan_abdulrahman_al_hindi_short,false))
        adhansound.add(SoundData("Abdul Ahmad Al Batal", R.raw.adhan_ahmad_al_batal,false))
        adhansound.add(SoundData("Abdul Ahmad Al Batal", R.raw.adhan_ahmad_al_batal_short,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
        adhansound.add(SoundData("Abdul Basit", R.raw.adhan_abdul_basit,false))
    }
}